version: 2

models:
  - name: SLV_EMPLOYEES__region
    description: "Contains information about the regions where employees are located (cleaned)."
    columns:
      - name: region_id
        description: "Unique identifier of the region."
        data_tests:
          - not_null
          - unique

      - name: region_description
        description: "Description of the region."
        data_tests:
          - not_null
          - unique
      
      - name: last_modified
        description: "Timestamp of the last modification of the original record."
        data_tests:
          - not_null
      
      - name: silver_loaded_at
        description: "Timestamp of when the record was loaded into the silver layer."
        data_tests:
          - not_null


  - name: SLV_EMPLOYEES__territories
    description: "Contains information about the territories assigned to employees (cleaned)."
    columns:
      - name: territory_id
        description: "Unique identifier of the territory."
        data_tests:
          - not_null
          - unique
      
      - name: territory_description
        description: "Description of the territory."
        data_tests:
          - not_null
      
      - name: region_id
        description: "Identifier of the region to which the territory belongs."
        data_tests:
          - not_null
      
      - name: last_modified
        description: "Timestamp of the last modification of the original record."
        data_tests:
          - not_null
      
      - name: silver_loaded_at
        description: "Timestamp of when the record was loaded into the silver layer."
        data_tests:
          - not_null


  - name: SLV_EMPLOYEES__employees
    description: "Contains employee information including contact details and address (cleaned)."
    columns:
      - name: employee_id
        description: "Unique identifier of the employee."
        data_tests:
          - not_null
          - unique

      - name: last_name
        description: "Last name of the employee."
        data_tests:
          - not_null

      - name: first_name
        description: "First name of the employee."
        data_tests:
          - not_null

      - name: title
        description: "Job title of the employee."
        
      - name: title_of_courtesy
        description: "Title of courtesy for the employee."
        
      - name: birth_date
        description: "Birth date of the employee."
        
      - name: hire_date
        description: "Hire date of the employee."
        
      - name: address
        description: "Address of the employee."
        
      - name: city
        description: "City where the employee is located."
        
      - name: region
        description: "Region or state where the employee is located."
        
      - name: postal_code
        description: "Postal code of the employee's address."
        
      - name: country
        description: "Country where the employee is located."
        
      - name: home_phone
        description: "Home phone number of the employee."
        
      - name: extension
        description: "Extension number for the employee's phone."
      
      - name: notes
        description: "Notes related to the employee."
      
      - name: reports_to
        description: "Identifier of the employee to whom this employee reports."
      
      - name: photo_path
        description: "Path to the employee's photo."

      - name: last_modified
        description: "Timestamp of the last modification of the original record."
        data_tests:
          - not_null

      - name: silver_loaded_at
        description: "Timestamp of when the record was loaded into the silver layer."
        data_tests:
          - not_null


  - name: SLV_EMPLOYEES__employee_territories
    description: "Contains information about the territories assigned to employees (cleaned)."
    columns:
      - name: employee_id
        description: "Unique identifier of the employee."
        data_tests:
          - not_null

      - name: territory_id
        description: "Identifier of the territory assigned to the employee."
        data_tests:
          - not_null

      - name: last_modified
        description: "Timestamp of the last modification of the original record."
        data_tests:
          - not_null

      - name: silver_loaded_at
        description: "Timestamp of when the record was loaded into the silver layer."
        data_tests:
          - not_null
