version: 2

models:
  - name: SLV_SHIPPERS__shippers
    description: "Contains shipper information including contact details and address (cleaned)."
    columns:
      - name: shipper_id
        description: "Unique identifier of the shipper."
        data_tests:
          - not_null
          - unique

      - name: company_name
        description: "Name of the shipper company."
        data_tests:
          - not_null
          - unique

      - name: contact_name
        description: "Name of the contact person at the customer's company."

      - name: phone
        description: "Phone number of the shipper company."
      
      - name: last_modified
        description: "Timestamp of the last modification of the original record."
        data_tests:
          - not_null
      
      - name: silver_loaded_at
        description: "Timestamp of when the record was loaded into the silver layer."
        data_tests:
          - not_null
